
remote_theme : tocttou/hacker-blog

title: Hooni's Blog
description: "TIL Blog for Hooni"
author:
name: "SomeHacker"
email: "jhoon2816@gmail.com"
url: "https://jhoon2816.github.io"
baseurl: ""

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2018"

